### ISSUE TITLE
Problem installing: GC_jmp_buf multiple definition

### ISSUE THREAD

**Issue by nikos-alexandris** [fasterthanlime/rock#1009]
Hello, i'm trying to install ooc on fedora 34 x86_64 linux with gcc 11.1.1 and when i run make rescue it fails with multiple linker errors stating that GC_jmp_buf has been defined multiple times. Specifically, it seems that it is trying to define it in /rock/vendor-prefix/lib/libgc.a when it has been defined in rock/vendor-build/../vendor/gc/include/private/gc_priv.h:2316
Does anyone have a fix for this?

**Comment by horasal** [comment]
It seems that libgc in vendor is a little outdated - it's still 7.2e (published in 2013).
also I noticed that libgc does fix a similar problem  in 2017 [here](https://github.com/ivmai/bdwgc/blob/master/ChangeLog#L1172)

clone latest gc and try again may help 

```
mv vendor/gc vendor/gc1
git clone https://github.com/ivmai/bdwgc vendor/gc
cd vendor/gc && ./autogen.sh && cd ../../
make rescue
```

**Comment by nikos-alexandris** [comment]
Worked like a charm! Thanks!
