### ISSUE TITLE
Funny issues with generics and varargs

### ISSUE THREAD

**Issue by fredreichbier** [fasterthanlime/rock#346]
Fun stuff!

```ooc

import structs/HashBag

Pair: class <K, V> {
    k: K
    v: V

    init: func (=k, =v) {}
}

//operator => <K, V> (k: K, v: V) -> Pair { Pair<K, V> new(k, v) }
    
hashbag: func (args: ...) {
    args each(|arg|
        pair := arg as Pair
        VV := pair V
        val := pair v as VV
    )
}

hashbag(Pair new("Hello", "World!"), Pair new("leet", 1337))
```

This segfaults. If we change the last line to

```ooc
hashbag(Pair new("Hello", "World!"))
```

it doesn't. Just adding this here for the records, I'll have a look at it and report more details later.

**Comment by fasterthanlime** [comment]
@fredreichbier @shamanas well you both lost! sucks to be y'alllllllllll

*drops :microphone:*

**Comment by fasterthanlime** [comment]
(Note: `Type owner` is still veeery experimental but it does solve that exact case. I'm pretty sure by poking around we can find other similar problems, and solve them accordingly)
