### ISSUE TITLE
Rock has trouble with array return types

### ISSUE THREAD

**Issue by shamanas** [fasterthanlime/rock#348]
The following code works:
<pre lang="ooc">
f: func -> SSizeT[] {
    return [1,2,3,4]
}
</pre>
However, it causes rock to go nuts (ERROR Couldn't add { } after [1, 2, 3, 4] in scope.) when autoreturn is used, such as:
<pre lang="ooc">
f: func->SSizeT[] {
    [1,2,3,4]
}
</pre>

**Comment by fasterthanlime** [comment]
The ArrayLiteral code is a clusterfuck btw :(
