### ISSUE TITLE
Generic type parameters can be overwritten

### ISSUE THREAD

**Issue by nddrylliog** [fasterthanlime/rock#415]
This is, hands down, the funniest bug I have ever encountered in ooc:

```ooc


import structs/ArrayList

main: func {

    s := ArrayList<Int> new()
    s add(0xdeadbeef). add(0). add(0). add(0)

    "Correct" println()
    for (i in 0..s size) {
        "%x" printfln(s get(i))
    }

    s T = Octet // that is so, so wrong.

    "Incorrect" println()
    for (i in 0..s size) {
        "%x" printfln(s get(i))
    }

}
```

/cc @shamanas @showstopper

**Comment by shamanas** [comment]
I've implemented this one of my branches, seems the sdk uses that (text/json/Parser.ooc)

```ooc
pushSimpleValue: func (token: Token@) {
        T: Class
        valuePtr := _parseSimpleValue(token&, T&)
        cell := Cell<Pointer> new((valuePtr as Pointer*)@) // TODO: EVIL, evil hack.
        cell T = T
        stack data add(cell)
    }
```

**Comment by davidhesselbom** [comment]
Parser makes valgrind go nuts about invalid memory usage...

**Comment by shamanas** [comment]
@davidhesselbom I'll take a look at it later today, I may rewrite it if it needs to be (of course, exposing the same API)

**Comment by fasterthanlime** [comment]
> Parser makes valgrind go nuts about invalid memory usage...

@davidhesselbom even when setting the following environment variable `GC_DONT_GC=1` ? It's a well-known fact that the Boehm GC and Valgrind don't play well together at all.

**Comment by davidhesselbom** [comment]
Hmm, I could try on Monday. But I get it with the GC off entirely, so, should that flag make any difference?

**Comment by fasterthanlime** [comment]
@davidhesselbom probably not
