### ISSUE TITLE
Misplaced oocdocs generate unhelpful errors

### ISSUE THREAD

**Issue by duckinator** [fasterthanlime/rock#565]
```ooc
/// test
"meep" println()
```

results in this oh-so-familiar error:

```
./test.ooc:1:0 ERROR Expected include, import, statement or declaration

/// test

```

Perhaps something like "Unexpected oocdoc comment." would be more appropriate?

**Comment by fasterthanlime** [comment]
<img width="493" alt="screen shot 2015-07-10 at 03 11 00" src="https://cloud.githubusercontent.com/assets/7998310/8610361/56aa8286-26b1-11e5-9338-819768bf1f48.png">

Both in top-level (Module) and function bodies. Might not be so in scopes though.. good candidate for a follow up some time in the future when I feel like touching that again.

**Comment by fasterthanlime** [comment]
Also, the token positions are.. funky, to say the least. Might be related to #898? Hard to tell.
