### ISSUE TITLE
Reassigning references can lead to "No such function" errors.

### ISSUE THREAD

**Issue by duckinator** [fasterthanlime/rock#595]
```ooc
x: func {
    a : Int@ = gc_malloc(Int size)
    a = 0
    func { ret := a }
}
```

=>

```
./test.ooc:3:9 ERROR No such function __test_closure223(Int@)
    a = 0
        ~
[FAIL]
```

Removing the `ret:=a` fixes it.

**Comment by fasterthanlime** [comment]
Well, now the error message is even more ironic...

<img width="1022" alt="screen shot 2015-07-10 at 00 46 13" src="https://cloud.githubusercontent.com/assets/7998310/8608647/17233ef0-269d-11e5-96b9-3f5484244725.png">
