### ISSUE TITLE
Function types don't work well with template covers

### ISSUE THREAD

**Issue by duckinator** [fasterthanlime/rock#626]
Not really sure of all the details of this, but:

Code:
```ooc
Foo: cover template<T> {
    fn: Func <T> (T)
    init: func(=fn)
}

Bar: class { clear: func }

Foo<Bar> new(Bar clear) // NOTE: without <Bar>, this segfaults.
// shamanas: Sorry to hijack this, edited for arguments that should work
```

Output:

```
$ rock test.ooc 
Resolving Foo<Bar> to a cover template!
Should get a template instance of CoverDecl Foo as per Foo<Bar>
Creating instance with fingerprint: __Foo__Bar
name T, ref ClassDecl Bar

ooc/test/test.ooc:8:1 ERROR No such function new(Func (Bar)) for `__Foo__BarClass`
Foo<Bar> new(Bar clear)
.~~~~~~~~~~~~           
[FAIL]
$ 
```

(Ignore the random . added so github would stop barfing on the formatting)

**Comment by zhaihj** [comment]
Now rock checks the typeargs. 

So I guess this issue may have been solved?

My tests:

Valid code: (compiles and run)
```ooc
Foo: cover template<T> {
    fn: Func <T> (T)
    init: func(=fn)
}
Bar: class { clear: static func<T>(a:T) }
Foo<Bar> new(Bar clear)
```

Invalid code A: (error, non static func will take `this` as the first parameter)

```ooc
Foo: cover template<T> {
    fn: Func <T> (T)
    init: func(=fn)
}
Bar: class { clear: func<T>(a:T) }
Foo<Bar> new(Bar clear)
```

```
test.ooc:8:10 error No such function new(Func <T> (Bar, T)) for `__Foo__BarClass`

Foo<Bar> new(Bar clear) // NOTE: without <Bar>, this segfaults.
         ~~~                                                   

test.ooc:3:5 info Nearest match is `static __Foo__Bar new(=fn) -> __Foo__Bar`
..but the arg `Bar clear` should be of type `Func <T> (T)` instead of `Func <T> (Bar, T)`


    init: func(=fn)
    ~~~~           

[FAIL]
```


Invalid code B: (error, can not assign normal function (accpets value) to generic function (accepts pointer))

```ooc
Foo: cover template<T> {
    fn: Func <T> (T)
    init: func(=fn)
}
Bar: class { clear: static func(a: Int) }
Foo<Bar> new(Bar clear)
```


```
test.ooc:6:10 error No such function new(Func (Int)) for `__Foo__BarClass`

Foo<Bar> new(Bar clear)
         ~~~           

test.ooc:3:5 info Nearest match is `static __Foo__Bar new(=fn) -> __Foo__Bar`
..but the arg `Bar clear` should be of type `Func <T> (T)` instead of `Func (Int)`


    init: func(=fn)
    ~~~~           

[FAIL]
```

**Comment by fasterthanlime** [comment]
@zhaihj I noticed you're now using `Foo` instead of `foo` as class name :) That makes me happy. Another thing: can you write tests in the format used in rock's official test suite? Using sam-assert (`describe`, `expect`), making sure there's something to run rather than just it compiling, so we can see if it crashes at runtime.

**Comment by zhaihj** [comment]
Yes, I will make sure all tests use sam-asset from now on.
Just a small question, should tests use sam-asset explictly? Because I find you removed `use sam-asset` from some tests.

**Comment by fasterthanlime** [comment]
`sam-assert`, not asset ;)

Yes, for some tests I used to add `use sam-assert` myself (when it made rock crash for example, so I had to launch rock via gdb), but now that we have the `--use=sam-assert` option for rock it's not necessary.

So I never put `use sam-assert` on top of tests anymore. Except if they crash rock you can just write a new test in `test/compiler/something/sometest.ooc` and run:

```bash
sam test --test test/compiler/something/sometest.ooc
```

**Comment by fasterthanlime** [comment]
In case you're not in our [mailing list](https://groups.google.com/forum/#!forum/ooc-lang), I improved the documentation of sam on ooc-lang.org: https://ooc-lang.org/docs/tools/sam/
