### ISSUE TITLE
Fix the way rock determines the type of binary operator expressions

### ISSUE THREAD

**Issue by shamanas** [fasterthanlime/rock#632]
See here:
```ooc
 if(!replaced && inferredType == null) {
    // that's probably not right - for example, for integer/float types promotion, etc.
    inferredType = left getType()
}
```

This should have no side effects and is really easy to implement, will be doing it in a couple (maybe more) hours as well as trying to solve some additional issues.

(Also, irrelevant, but I may start up a blog and write about the whole findCommonRoot thingy. Also, string interpolation.)

Edit: because of pointer arithmetic (and perhaps other issues I have not crossed yet), this appears to be an issue which cannot be solved with findCommonRoot and a bit of tweaking

**Comment by davidhesselbom** [comment]
In C,
```c
#include <stdio.h>
#include <stdlib.h>

int main ()
{
	printf("%.2f\n", 1.0f/3);
	printf("%.2f\n", 1/3.0f);
	return (0);
}

// Output:
// 0.33
// 0.33
```
but in ooc,
```ooc
println((1.0f/3) toString())
println((1/3.0f) toString())

// Output:
// 0.33
// 0
```

**Comment by zhaihj** [comment]
@davidhesselbom 
in fact a patch is almost finished. It's just lying in my fork.

**Comment by zhaihj** [comment]
I've been using the patch for a while and it works well.
If anyone would like to test it, I will file a pull request.

https://github.com/zhaihj/rock/commit/873196cc0d1dc1423a9c87b2ab4c1ac48c359c87
https://github.com/zhaihj/rock/commit/efa1c8b47ee39baae4b7185e6be7aa833c937075
https://github.com/zhaihj/rock/commit/e2e314b677efcf6165e46652eb1ace2ae4e6f1d8
https://github.com/zhaihj/rock/commit/2ec5493326fc57f1ddcacb7b64518564323b80e9
