### ISSUE TITLE
::= syntax in covers

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#782]
Why can't covers use the ::= syntax?

``` ooc
import math

// Does not build
PointCoverA : cover {
    x, y: Float
    Norm ::= (this x pow(2.0f) + this y pow(2.0f)) sqrt()
}

// Builds just fine
PointCoverB: cover {
    x, y: Float
    Norm: Float { get { (this x pow(2.0f) + this y pow(2.0f)) sqrt() } }
}

// Builds just fine
PointClassA: class {
    x, y: Float
    Norm ::= (this x pow(2.0f) + this y pow(2.0f)) sqrt()
}

// Builds just fine
PointClassB: class {
    x, y: Float
    Norm: Float { get { (this x pow(2.0f) + this y pow(2.0f)) sqrt() } }
}
```

**Comment by davidhesselbom** [comment]
Can this be made to work for static properties as well? Or does it already? What would be the syntax, then?
```ooc
property: static := 1
```
???

**Comment by shamanas** [comment]
I would expect the syntax to be  

```ooc
// The "static expr" is kinda funky but it actually works and is idiomatic in ooc
prop ::= static 1
```

(If it does work, that is)

**Comment by davidhesselbom** [comment]
I know this was closed long ago, but I'm wondering about something related, and I don't think I should open a new issue about it. Here goes:

Can covers have set properties?
```ooc
Vector: cover {
    x, y: Int
    init: func
}
Size: cover from Vector extends Vector {
    init: func
    width: Int {
        get { this x }
        set(value) { this x = value }
    }
    height: Int {
        get { this x }
        set(value) { this x = value }
    }
}
```
This doesn't build, because 
```
error: lvalue required as left operand of assignment
         set(value) { this x = value }
```
and I'm not even sure what that means.

**Comment by davidhesselbom** [comment]
I hadn't thought about
```ooc
    width: extern (x) Int
    height: extern (y) Int
```
which is obviously a much, much better way of doing it in this particular case.

**Comment by fasterthanlime** [comment]
@davidhesselbom actually that's an interesting bug

**Comment by davidhesselbom** [comment]
What is?

Btw, do you still need the `extern` keyword, or is there another syntax I should use when the cover I'm a cover from isn't... external?

**Comment by fasterthanlime** [comment]
@davidhesselbom your `am I missing a @ somewhere` comment made me think that this bit of code would fail:

```ooc
Foo: cover {
    bar: Int

    baz: Int {
        set (baz) { this bar = baz }
    }
}

f: Foo
f bar = 1
f baz = 2

if (f bar != 2) {
    raise("expected f bar == 2")
}
```

..but it actually works so it must be linked to the `extends`

**Comment by fasterthanlime** [comment]
Whereas this doesn't work:

```ooc
UnderFoo: cover {
    bar: Int
}

Foo: cover from UnderFoo extends UnderFoo {
    baz: Int {
        set (baz) { this bar = baz }
    }
}

f: Foo
f bar = 1
f baz = 2

if (f bar != 2) {
    raise("expected f bar == 2")
}
```

**Comment by davidhesselbom** [comment]
Does it fail the test at the end, or does it simply not build?

**Comment by fasterthanlime** [comment]
@davidhesselbom I opened #949 to track it — but I won't have time to close it.

**Comment by davidhesselbom** [comment]
Ok, thanks though.

I'll ask again about the other thing: Is there an alternative to `width: extern (x) Int` when creating a `cover from` a cover that doesn't come from an external library, or is `extern` simply the keyword for `declared in another cover, somewhere, but not here`?

**Comment by fasterthanlime** [comment]
@davidhesselbom no alternative that I know of. an `extern` name is the `underlying name of a field declared somewhere else`

**Comment by davidhesselbom** [comment]
Okay, just making sure. Thanks!
