### ISSUE TITLE
Parameter of type Object matches first type of Cell<T> regardless of T's type

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#802]
```ooc
write: func(data: Object) {
	(match (data) {
		// This below case matches Cell<T> for any T, which is a problem related to how generic types are implemented
		case c: Cell<String> =>
			"To get here I should be a Cell<String> but apparently I'm a " + c class name + "<" + c T name + ">"
		case cell: Cell<Int> =>
			cell get() toString()
		case =>
			"FAIL"
	}) println()
}
write(Cell new(2))
```
outputs
>`To get here I should be a Cell<String> but apparently I'm a Cell<Int>`

**Comment by davidhesselbom** [comment]
> Beyond that, I still think it's a better idea to nest matches by hand.

Can you give an actual example that allows me to match on the `T` in `Cell<T>` after I've matched on `Cell`?
```ooc
write: func <T> (data: Object) {
    (match (data) {
    // "case value: Cell =>" won't build because "No type parameters for Cell. It should match Cell",
    // as already mentioned, so doing "Cell<Object>" instead
		case value: Cell<Object> =>
			(match (value T) {
				case valTee: String =>
					value get()
	        	case valTee: Int =>
            		value get() toString()
            })
        case =>
            "FAIL"
    }) println()
}
```
This won't build because "No such function toString() for `Object`". Fair enough, but if I change it to
```ooc
case value: Cell<String> =>
    (match (value T) {
    case valTee: String =>
        value get()
    case valTee: Int =>
        value get() as Int toString()
```
I instead get the error `Missing info for type argument T. Have you forgotten to qualify write<T> (data : Object :Object), e.g. List<Int>?` on the call `write(Cell new(2))`. This may very well be a legit error, but I don't know how to fix it. It *sounds* to me as if I'm supposed to write `write<Cell>(Cell new(2))`, which I'm pretty sure was exactly what you said you didn't like about how other languages do generics. It also makes rock segfault... :)

Ok, so let's ignore the function that takes an Object for now, and try something simpler: A function that takes `Cell<T>`:
```
write: func <T> (data: Cell<T>) {
    (match (data T) {
        case value: String =>
            data get() as String
        case value: Int =>
       	    data get() as Int toString()
        case =>
            "FAIL"
    }) println()
}
write(Cell new(2)) // prints "FAIL"
write(Cell new("Hello")) // also prints "FAIL"
```
Well, that didn't work.

What about `(Cell<T>, T)`?
```
write: func <T> (data: Cell<T>, t: T) {
    (match (data T) {
        case value: String =>
            data get() as String
       	case value: Int =>
            data get() as Int toString()
        case =>
            "FAIL"
    }) println()
}
```
Well, `C compiler failed on module testtestest from testtestest, bailing out`. Obviously, I have no idea what I'm doing anymore. Help?

**Comment by fasterthanlime** [comment]
It's kind of hard to read through all that so it's entirely possible that I missed soemthing, but I noticed something.

You can either do

```ooc
cell: Cell<T>
match (cell T) {
  case Int =>
    i := cell get() as Int
  case Float =>
    f := cell get() as Float
}
```

(which is long-form), or you can do the short form:

```ooc
cell: Cell<T>
match (cell get()) {
  case i: Int =>
    // whatever
  case f: Float =>
    // whatever
}
```

But above, you're conflating the two, so there's no chance it'll work :) Don't confuse generic values & generic types.

**Comment by fasterthanlime** [comment]
@davidhesselbom here's a full example that works well for me:

```ooc

Whatever: class { init: func }

write: func ~noCell <T> (t: T) {
    write(Cell new(t))
}

write: func <T> (cell: Cell<T>) {
    match (cell get()) {
        case i: Int =>
            "Got int #{i}" println()
        case f: Float =>
            "Got float #{f}" println()
        case =>
            "Got other type #{cell T name}" println()
    }
}

write(42 as Int)
write(3.14 as Float)
write(Whatever new())
```

**Comment by fasterthanlime** [comment]
(And indeed, it's a pity that the second `write` here needs a `<T>`, it shouldn't. I think `Cell<?>` syntax should exist. The compiler check for unqualified generic types is probably too severe, but believe me, it did a lot of damage control back in the days...)

**Comment by davidhesselbom** [comment]
Splendid, thank you sir!

**Comment by fasterthanlime** [comment]
No problem. Sorry it took a long-ass issue for this info to get out. It'd be probably right at home somewhere at https://github.com/fasterthanlime/ooc-lang.org/blob/master/content/docs/lang/generics.md, perhaps in a more documentation-y formulation. If someone has time, don't hesitate to send in a pull request.

**Comment by davidhesselbom** [comment]
I'll look into it. Meanwhile, I gave you another, much smaller one :)

**Comment by fasterthanlime** [comment]
So, matching the actual typeArgs should be another issue (if at all), but matching generic types without specifying typeArgs at all is now possible.
