### ISSUE TITLE
Parameter defaults are awesome, but undocumented

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#808]
I can do
```ooc
import lang/IO
aFunction: func (value := 2) { value toString() println() }
aFunction(1) // prints 1
aFunction() // prints 2
```
which is totally awesome, but not mentioned anywhere in the ooc documentation as far as I can tell. I was missing out until another guy tried it assuming it would just work, and it did :)

So then I tried to do
```ooc
testClass: class {
	value: Int
	init: func (=value := 4)
}
```
Which didn't fly:
> error Malformed function argument (remember, it's `name: Type` in ooc, not `Type name`)

Unless anyone thinks this is a terrible idea, I'll see if I can figure out how hard it would be to get this to work (maybe with a slightly different syntax, like `init: func (=value = 4)`, dropping the `:`). I guess Nagaqueen.c is a good place to start?

**Comment by fasterthanlime** [comment]
Original issue closed in https://github.com/fasterthanlime/ooc-lang.org/commit/8ee8033c6c5c51f3148b4056b6b039ea8b530c86 — feature request is a separate thing.

**Comment by fasterthanlime** [comment]
(Note: not deployed the website yet, but will do)
