### ISSUE TITLE
First gc_malloc(> 131048) call with --gc=off returns absurd pointers

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#815]
I've discovered a magic number! :tada: 

If I run this piece of code with `--gc=off -lpthread`
```ooc
pointerA: UInt8* = 0
pointerB: UInt8* = 0
pointerC: UInt8* = 0

sizeA: Int = 131048

pointerA = gc_malloc(sizeA)
pointerA toString() println()

sizeB: Int = 131048

pointerB = gc_malloc(sizeB)
pointerB toString() println()

sizeC: Int = 131049

pointerC = gc_malloc(sizeC)
pointerC toString() println()
```
it will output three numbers that are 7 or 8 digits long. 

If, however, `sizeA` is any number higher than `131048`, only `pointerB` will be a number of 7 or 8 digits, while `pointerA` and `pointerC` will be 15 digits long and in the `0x7EF0_0000_0000` to `0x7FFF_FFFF_FFFF` range (is my guess, from the 50 or so times I tried). Obviously, when trying to access these pointers, I get segfaults since I don't have 140+ TB of RAM.

I've looked for documentation on the underlying `calloc` call but so far I haven't found anything about this.

I've confirmed this on three different Ubuntu machines, running rock on the `stable` branch.

**Comment by fasterthanlime** [comment]
So, that's a pretty old issue, and unfortunately I don't think it has anything to do with rock :(

Just ran the following:

```ooc
pointerA: UInt8* = 0
pointerB: UInt8* = 0
pointerC: UInt8* = 0

sizeA: Int = 131048

pointerA = gc_malloc(sizeA)
"%p" printfln(pointerA)

sizeB: Int = 131048

pointerB = gc_malloc(sizeB)
"%p" printfln(pointerB)

sizeC: Int = 131049

pointerC = gc_malloc(sizeC)
"%p" printfln(pointerC)
```

Both with GC on and off, and it only gives me reasonable pointer values, not impossibly big ones. If you do manage to find out where it's from, and it's caused by rock, don't hesitate to re-open. Otherwise.. it'll remain a mystery!

**Comment by davidhesselbom** [comment]
I meant to revisit a few old issues and close any I didn't need fixing to save you some time, but you beat me to it. Will re-open if it ever turns out to be an actual problem.
