### ISSUE TITLE
Rock infers generic type exclusively from the first instance it can

### ISSUE THREAD

**Issue by shamanas** [fasterthanlime/rock#825]
```ooc
Foo: class { init: func }
Bar: class extends Foo { init: super func }

f: func <T> (a, b: T) {
    T name println()
}

f (Bar new(), Foo new())
```

This should print Foo but it prints Bar, as T is infered from the first argument it appears in a.  
Instead, findCommonRoot should be used here.

**Comment by fasterthanlime** [comment]
Ooh, that looks good

<img width="880" alt="screen shot 2015-07-09 at 22 39 33" src="https://cloud.githubusercontent.com/assets/7998310/8606362/6d795670-268b-11e5-9443-99ec672ae8c8.png">

**Comment by vendethiel** [comment]
Just a question... what is the performance impact of such unification with say, an array literal of 500 elements?

**Comment by fasterthanlime** [comment]
Ehhh now is not the time for such questions.

**Comment by fasterthanlime** [comment]
(But it'd be interesting to make a stress test & optimize from there. Later.)

**Comment by fasterthanlime** [comment]
So, there'll probably be about a dozen duplicates of this in the future.. but at least for this case, I have a fix.

I've tried going further but then the sdk starts showing cracks everywhere so uh, better left for another time. At least we're on the path to basic sanity.

**Comment by vendethiel** [comment]
fair enough ;-)
