### ISSUE TITLE
Rock does not type check arguments of generic type that was infered in the same call

### ISSUE THREAD

**Issue by shamanas** [fasterthanlime/rock#826]
An example should be simpler to understand:

```ooc
// This compiles
Foo: class <T> {
    init: func(a, b: T)
}

foo := Foo new(1, "lol")

// This too
f: func <T> (a, b: T)

f("what", 12)
```

**Comment by fasterthanlime** [comment]
Looks like it was fixed at the same time as #825

<img width="814" alt="screen shot 2015-07-10 at 20 59 09" src="https://cloud.githubusercontent.com/assets/7998310/8626743/87bae984-2746-11e5-803a-b4963443b18a.png">
