### ISSUE TITLE
Double // on one line won't compile

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#829]
Double-commenting a line causes rock to fail with `Expected include, import, statement or declaration`, which is annoying when you're trying to debug your code by commenting things out. Can this please be changed?

**Comment by zhaihj** [comment]
I noticed that cogneco has some commits about ooc-doc but can not find the clone of nagaqueen.... Is that private?

Also, I've tested my patch for a while and everything seems good. Remaining task is adding warnings for the mis-placed ooc-docs. But I can not figure out a smart way to do it.

**Comment by davidhesselbom** [comment]
Cogneco has no fork of nagaqueen, because @fredrikbryntesson is the only person working on it so far. It's not private: https://github.com/fredrikbryntesson/nagaqueen

**Comment by zhaihj** [comment]
Thank you! 
I'll wait for updates :)
