### ISSUE TITLE
Overriding final function builds, but segfaults when run

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#851]
This builds, but when you run the program, it segfaults. I don't think it should build in the first place. Is this a bug?
```ooc
First: class {
	init: func
	test: final func
}

Second: class extends First {
	init: func
	test: func
}

s := Second new()
s test()
```

**Comment by zhaihj** [comment]
I think it should be disallowed. 
Inheriting from a final function makes no sense.

But how should we do with cover? It seems that every function in cover is final.

**Comment by zhaihj** [comment]
Some related problem:

	First: class {
		init: func
		test: func
	}

	Second: class extends First {
		init: func
		test: final func
	}

	s := Second new()
	s test()

By compiling the above code, I get:

	test.ooc: In function ‘test__Second_class’:
	test.ooc:28:29: error: ‘test__Second_test_impl’ undeclared (first use in this function)

Final func does not have an impl, but rock is still using _impl when accessing it.

            .test = (void*) test__Second_test_impl,

**Comment by fasterthanlime** [comment]
Seems like this has been fixed in master, not sure why this bug is still open!
