### ISSUE TITLE
Improve operator overloading

### ISSUE THREAD

**Issue by zhaihj** [fasterthanlime/rock#857]
I'm playing with operator overloading. But it seems that operator as is not so easy to use...

1. If operator `as` is a member of class/cover, it is not even be searched. (Because rock only searches in modules) 

2. It's really difficult to implement a as function returning generic arg, for example:

		operator as <T,R> (other: array<T>) -> array<R> {
			"casted" println()
			ret := array<R> new(other length)
			if(T size == R size){
				memcpy(ret data, other data, other length * T size)
				return ret
			}
			if(T size > R size){
				Exception new( \
					"cast type with size %d to type with size %d may cause overflow" \
					format(T size, R size)) throw()
			}
			for(i in 0..ret length){
				ret[i] = other[i] as R
			}
			ret
		}

Things like this do not really work because return's type can not be inferred. But "generic func" is not properly implemented in parser (but sdk is using it everywhere).

* operator does not support suffixes.  thing like

		operator as ~sizet ( ...

is not allowed. It means that we can not even create different funcs for different types. for example:

	   operator as <T> (a: array<T>) -> array<Int8>
	   operator as <T> (a: array<T>) -> array<Int16>

will cause c compilation error because types are not parts of function name.

**Comment by davidhesselbom** [comment]
> Things like this do not really work because return's type can not be inferred. But "generic func" is not properly implemented in parser (but sdk is using it everywhere).

How does the SDK use it everywhere if it doesn't work properly?

**Comment by zhaihj** [comment]
Try this

	foo: func <T> (myInt: T) -> String {
		match(myInt){
			case a: Int => return a toString()
			case => Exception new("error") throw()
		}
		""
	}

	foo(1) // Call1
	foo<Int>(1) //Call2

Call2 will cause segmentation. SDK uses template function everywhere but they are always called without typeargs. This is why it works.

**Comment by davidhesselbom** [comment]
Ah. Gotcha.

**Comment by fasterthanlime** [comment]
I'm going to link that post here, because I talk about this issue specifically, and also #855, and most things you've proposed, @zhaihj: http://fasterthanlime.com/blog/2015/ooc-generics-and-flawed-designs/

Sorry.

**Comment by zhaihj** [comment]
Interesting & thank you for reply.
Now I think I begin caching the thoughs of the design of ooc. #855 seems to go to a different direction. I'll close it.

I opened this issue because I'm trying to implement a new array (with cover template). I've expected to solve the problem that array can not be porperly casted (as function return, arguments, etc). But it is not so easy. In fact I still have no idea how to make it work. But now I can go on :)
