### ISSUE TITLE
Variables declared in tuple may conflict with function parameters.

### ISSUE THREAD

**Issue by zhaihj** [fasterthanlime/rock#863]
When trying to compile something like this:

	foo: func(i: Int) -> Int{
		(a, i) := ("test", 2)

		i
	}

rock generates:

	lang_Numbers__Int tuple__foo(lang_Numbers__Int i) {
		#line 2 "/home/housezet/complier/bug/tuple.ooc"
		lang_String__String* a = __tuple_strLit1;
		#line 2 "/home/housezet/complier/bug/tuple.ooc"
		lang_Numbers__Int i = 2;
		#line 4 "/home/housezet/complier/bug/tuple.ooc"
		return i;
	}

and finally:

	INSERT$ rock tuple                    
	/home/housezet/complier/bug/tuple.ooc: In function ‘tuple__foo’:
	/home/housezet/complier/bug/tuple.ooc:2:23: error: ‘i’ redeclared as different kind of symbol
		 (a, i) := ("test", 2)
						   ^
	rock_tmp/ooc/tuple/tuple.c:43:48: note: previous definition of ‘i’ was here
	 lang_Numbers__Int tuple__foo(lang_Numbers__Int i) {
													^
	/home/housezet/complier/bug/tuple.ooc:2:26: warning: unused variable ‘a’ [-Wunused-variable]
		 (a, i) := ("test", 2)
							  ^
	C compiler failed on module tuple from tuple, bailing out

	[FAIL]

but this works even though it may not output correctly:

	i: Int = 1
	(a, i) := (1, 2)
	i toString() println()

This prints `1` instead `2` beacuse a new variable `tuple_i` is generated (but can never be used, of course).

**Comment by fasterthanlime** [comment]
So, the correct behaviour is to disallow such a declaration.

```ooc
foo: func (i: Int) {
  i := 4 // rock should err
}
```

Same goes for tuple declarations.

**Comment by fasterthanlime** [comment]
Making progress

<img width="447" alt="screen shot 2015-07-08 at 09 47 25" src="https://cloud.githubusercontent.com/assets/7998310/8565456/5e68f82e-2556-11e5-8f88-57614afb567c.png">

**Comment by vendethiel** [comment]
Is this going inside some test/ folder?

**Comment by fasterthanlime** [comment]
Even better:

<img width="553" alt="screen shot 2015-07-08 at 10 01 51" src="https://cloud.githubusercontent.com/assets/7998310/8565712/687ca764-2558-11e5-97fe-c1c61b241882.png">

@vendethiel Well, it should. Messed it up for the previous few fixes, will do it for this one.

**Comment by vendethiel** [comment]
Great to hear :+1:
