### ISSUE TITLE
Syntax Highlighting for Sublime Text

### ISSUE THREAD

**Issue by runeimp** [fasterthanlime/rock#871]
It would be nice if the [Editors](http://ooc-lang.org/docs/tools/editors/) page could be updated to include Sublime Text with something like the following

## Sublime Text

Sublime Text has great support for TextMate bundles with the exception of commands. You can use the TextMate [ooc.tmbundle](https://github.com/nilium/ooc.tmbundle) to power the syntax highlighting for ooc within Sublime Text 2 and 3.

1. Find your Sublime Text [data directory](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/basic_concepts.html#the-data-directory).
2. Go to it via command line (CMD prompt, Terminal, etc.)
3. `git clone https://github.com/nilium/ooc.tmbundle.git`
4. restart Sublime Text
5. Associate the _ooc_ language with `.ooc` and `.use` files via the language selector in the bottom right of the window.

-or-

You can select something like Objective-C++ (built in) for _very_ basic syntax highlighting.

 * * *

I hope this may be useful and help adoption of this very fun language.  :-D

**Comment by fasterthanlime** [comment]
That sounds great. Can you do that as a pull request to https://github.com/fasterthanlime/ooc-lang.org ?

**Comment by runeimp** [comment]
Doh! I knew there was another repo with the site. Missed it in my scan earlier. In any case done.  :-D
