### ISSUE TITLE
Hello,new user here with a simple question!

### ISSUE THREAD

**Issue by Murii** [fasterthanlime/rock#872]
How can I compile occ to work on android(with sdl)?Are there any samples?Or maybe tutorials?

**Comment by fasterthanlime** [comment]
Hey murii, as far as I know this is the only piece written on the subject:

  * <http://fasterthanlime.com/blog/2013/ooc-android/>

Although it's a pretty specific setup (relies on SDL for most things, geared towards games). Also I'm not using it actively nowadays.
