### ISSUE TITLE
Problems using HashMap with covers / custom types?

### ISSUE THREAD

**Issue by geckojsc** [fasterthanlime/rock#874]
From what I've tested, the following program *sometimes* segfaults as map get(b) returns null:
```ooc
import structs/HashMap

Vec2: cover {
	x, y:Int
}

main: func {
	map := HashMap<Vec2, String> new()
	
	a := (10, 20) as Vec2
	b := (10, 20) as Vec2
	
	map put(a, "foo")
	map get(b) println()
}
```

I've tried the following assertions (assuming that these are the functions that were chosen by the HashMap).

```ooc
assert(genericEquals(a, b))
assert(murmurHash(a) == murmurHash(b)) // fails?
```

Strangely the 2nd one always fails, which is weird because I thought they should have identical bits, and also weird that the main program sometimes succeeds.

I was able to get a working solution by [defining custom hash functions](https://gist.github.com/geckojsc/6281d40ae8599722202f), though originally I was tripped up because I didn't realise they had to be implemented generically.

**Comment by zhaihj** [comment]
murmurHash may be unincorrect.

* Firstly `SizeT` should be `UInt32`;
* The code:

    data += 4
    if(len < 4) break
    len -= 4

will process extra 4 bytes. But in most time the bytes following value is 0, so it works.

This code should be 

    data += 4
    len -= 4
    if(len < 4) break

**Comment by fasterthanlime** [comment]
Ugh, another remnant from the big SizeT fight of.. 2011 ? I should've stood my ground back then.
