### ISSUE TITLE
Double closures = wrong byref closure capture

### ISSUE THREAD

**Issue by fasterthanlime** [fasterthanlime/rock#882]
Sample:

```ooc
Gift: cover {
  msg: String
  pad: Int
}

please: func (f: Func) { f() }

main: func {
  g := ("One", 0)

  please(||
    g = ("Two", 0)
    please(||
      g = ("Three", 0)
    )
  )

  g msg println()
}
```

## Expected behaviour

Print "Three"

## Current behavior

Print "Two" and writes to a random memory location.. which is really really bad. C compiler only emits a warning (`Gift*` vs `Gift**`)

**Comment by davidhesselbom** [comment]
Nice, need to see if this fixes #864.

**Comment by fasterthanlime** [comment]
Hey @davidhesselbom! Hmm no, looks like a different issue but it shouldn't be a hard fix.

Sorry about being the worst maintainer ever in the history of open source projects btw, just doing some selfish bugfixes because our engine for [Jaakan](https://jaakan.nevargames.com/blog/) is written in ooc.

**Comment by fasterthanlime** [comment]
@davidhesselbom well that wasn't hard at all :) props to @zhaihj for finding the erroneous comparison.
