### ISSUE TITLE
Sometimes Type typeArgs gets a VariableDecl instead of a TypeAccess

### ISSUE THREAD

**Issue by fasterthanlime** [fasterthanlime/rock#895]
For example in `__va_call`.. gotta investigate further.

**Comment by shamanas** [comment]
I have another instance:  

```ooc

use sam-assert

result := 0

describe("", ||
    foo := Foo<Bar> new(Bar clear)
    foo doThing()
    expect(42, result)
)

Foo: cover template<T> {
    fn: Func <T> (T)

    init: func@ (=fn)

    doThing: func {
        fn(42)
    }
}

Bar: class {
    clear: static func <T> (a: T) {
        match a {
            case i: Int =>
                result = i
        }
    }
}
```  

(At least on my branch)  
Which is literally one of the tests and passes correctly on Travis-CI :/

**Comment by shamanas** [comment]
TODO: When fixed, grep #895 and fix instances where I may handle both TypeAccesses and VariableDecls

**Comment by shamanas** [comment]
Writing some class template tests and I'm on this

**Comment by shamanas** [comment]
Ok, apparently FuncTypes have VariableDecl typeArgs (which make sense) but the overload of Type getTypeArgs returns a List of VariableDecl's instead of TypeAccesses.

**Comment by shamanas** [comment]
That explains __va_call too, since it has FuncType in its signature.
