### ISSUE TITLE
extern enum ?

### ISSUE THREAD

**Issue by zhaihj** [fasterthanlime/rock#899]
In the document of official site ( http://ooc-lang.org/docs/lang/enums/ )
It says:

Or, each element can be aliased individually:
```ooc
ShutdownParam: extern enum {
  extern(SHUT_RD) read
  extern(SHUT_WR) write
  extern(SHUT_RDWR) readWrite
}
```

However, when I try to compile it, rock gives:

```
INSERT$ rock test.ooc

 test.ooc:2:5 error Expected enum element!

    extern(SHUT_RD) read 
    ~                    

[FAIL]
```

**Comment by fasterthanlime** [comment]
Alright so extern enums (as in, using the `extern` keyword with an enum) is broken, I don't think it should even be allowed right now.

As for parameters that are in fact aliases, the doc is wrong, it should read:

```ooc
ShutdownParam: enum {
    read: extern(SHUT_RD)
    write: extern(SHUT_WR)
    readWrite: extern(SHUT_RDWR)
}
```

This, plus:

```ooc
SHUT_RD   : unmangled Int = 1
SHUT_WR   : unmangled Int = 2
SHUT_RDWR : unmangled Int = 3
```

Does compile.
