### ISSUE TITLE
Grouping imported files by path in .use files 

### ISSUE THREAD

**Issue by davidhesselbom** [fasterthanlime/rock#904]
In `.ooc` files, it's possible to write things like `use path/to/[File1, File2, AnotherFile]`. This doesn't seem to work with the `Imports:` directive in `.use` files, but would be neat.

**Comment by fasterthanlime** [comment]
As in, the 'Imports' directive of .use files?

**Comment by davidhesselbom** [comment]
Yes, I edited my answer to clarify. Sorry about being unclear.

**Comment by fasterthanlime** [comment]
No problem, just had me wondering for a while, "do namespaced usedefs even
exist?"
