### ISSUE TITLE
Setting by-ref member of underlying cover doesn't work

### ISSUE THREAD

**Issue by fasterthanlime** [fasterthanlime/rock#949]
This works:

```ooc
Foo: cover {
    bar: Int

    baz: Int {
        set (baz) { this bar = baz }
    }
}

f: Foo
f bar = 1
f baz = 2

if (f bar != 2) {
    raise("expected f bar == 2")
}
```

aka baz's setter accepts `this` by reference, correctly

But this doesn't:

```ooc
UnderFoo: cover {
    bar: Int
}

Foo: cover from UnderFoo extends UnderFoo {
    baz: Int {
        set (baz) { this bar = baz }
    }
}

f: Foo
f bar = 1
f baz = 2

if (f bar != 2) {
    raise("expected f bar == 2")
}
```

because it generates code like:

```c
void blah__Foo___setbaz__(blah__Foo* this, lang_Numbers__Int baz) {
    ((blah__UnderFoo)(*this)).bar = baz;
}
```

whereas it should be generating code like:

```c
void blah__Foo___setbaz__(blah__Foo* this, lang_Numbers__Int baz) {
    *((blah__UnderFoo*)this).bar = baz;
}
```

I'm fairly confident at this point `this` is a ReferenceType, so we should look into what goes on when you cast a ReferenceType to another

---

edit: even this code should work in fact:

```c
void blah__Foo___setbaz__(blah__Foo* this, lang_Numbers__Int baz) {
    *this.bar = baz;
}
```

because Foo is simply a typedef:

```c
typedef blah__UnderFoo blah__Foo;
```

and we know that in the AST because it's a cover-from, so we could just go ahead and ignore the cast

**Comment by fasterthanlime** [comment]
Originally reported by @davidhesselbom in #782

**Comment by davidhesselbom** [comment]
Maybe it's not important, but don't forget that
```ooc
Foo: cover from UnderFoo extends UnderFoo {
    baz: Int {
        get { this bar }
    }
}
```
works just fine.

**Comment by fasterthanlime** [comment]
@davidhesselbom a getter isn't by-ref, so the cast `Foo -> UnderFoo` works just fine (it's useless and ignored by the C compiler)

**Comment by davidhesselbom** [comment]
Oh.. right.

**Comment by davidhesselbom** [comment]
I also found this:
```ooc
Vector: cover {
    x, y: Int
    init: func@ (=x, =y)
}
Point: cover from Vector extends Vector {
    init: func@ (=x, =y)
}

point := Point new(2, 3)
point x toString() println()
```
fails to compile with
```
error: lvalue required as left operand of assignment
     init: func@ (=x, =y)
```
in `Point`'s constructor, but if I comment out `Point`'s constructor, I get
```
No such function new(Int, Int) for `PointClass`
```
Is this also a bug?

**Comment by davidhesselbom** [comment]
I also tried modifying `Point`'s constructor to
```ooc
    init: func@ (x, y: Int ) { this x = x; this y = y }
```
Same error: `lvalue required`...

**Comment by fasterthanlime** [comment]
@davidhesselbom same bug

**Comment by davidhesselbom** [comment]
This (also posted in #940 now) doesn't give quite the same error, but is perhaps related:
```ooc
import structs/ArrayList

Foos: class {
    init: func
    operator [] (index: Int) -> Foo {
        Foo new()
    }
}
Foo: cover {
    bar: Int
    init: func@
}

foos := Foos new()
list := ArrayList<Int> new()
list add(foos[0] bar)
```
This fails to build with the error 
```
lvalue required as unary ‘&’ operand
list add(foos[0] bar)
```
However, if that last line is changed to
```ooc
foo := foos[0]
list add(foo bar)
```
everything seems to work.

**Comment by shamanas** [comment]
Hmm, I wonder if the cast and deref happen i nthe middle end somewhere or are generated by the backend.  

I wish we had a flag that dumped the AST after all transformations in some format that could be easily visualized.

Anyway, I'll look into this today, though it looks like one of those things that is really difficult to track.

**Comment by shamanas** [comment]
This is actually an issue with any assignment to an extended cover value.  

The issue is the generated cast to a scalar type followed by the dot operator (which seems not to be an lvalue).  

I like Amos' solution of just generating `(*foo).bar` (for by-ref accesses) or `foo.bar` for any cover access, I guess I'll have to refresh my backend knowledge :P

**Comment by davidhesselbom** [comment]
Is there a way I can work around it without any of changes I found? Something like
```ooc
list add((foos[0]*)@ bar) // yes, I'm just making things up here
```
?

**Comment by shamanas** [comment]
@fasterthanlime  

It seems making rock never output casts for accesses to covers works and I think it is a correct thing to do.  

I cannot think of any edgecase, since cover "hierarchy" is expressed through typedefs.  
PR will be up in a bit.
