### ISSUE TITLE
Changes in slurped files do not cause recompilation of slurping modules.

### ISSUE THREAD

**Issue by davidpiuva** [fasterthanlime/rock#955]
It is most likely because the slerping module has not changed even thou the meaning has changed from the external file. One solution is to connect all slerped files as dependencies to the modules where they are placed.

Using `rock -x` before compiling solves the problem but is slower.

**Comment by shamanas** [comment]
Ah, that's an interesting bug.  

Adding the slurped files as dependencies seems liek the right thing to do, will take a look at it in a bit.
